/* Copyright (c) 2014, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_JD9366_VIDEO_H_
#define _PANEL_JD9366_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config jd9366_video_panel_data = {
	"qcom,mdss_dsi_jd9366_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution jd9366_video_panel_res = {
	800, 1280, 100, 100, 20, 0, 16, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info jd9366_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char jd9366_video_on_cmd1[] = {0x02,0x00,0x39,0xC0,0XE0,0x00,0xFF,0xFF};         
static char jd9366_video_on_cmd2[] = {0x02,0x00,0x39,0xC0,0XE1,0x93,0xFF,0xFF};
static char jd9366_video_on_cmd3[] = {0x02,0x00,0x39,0xC0,0XE2,0x65,0xFF,0xFF};
static char jd9366_video_on_cmd4[] = {0x02,0x00,0x39,0xC0,0XE3,0xF8,0xFF,0xFF};                            
static char jd9366_video_on_cmd5[] = {0x02,0x00,0x39,0xC0,0XE6,0x02,0xFF,0xFF};
static char jd9366_video_on_cmd6[] = {0x02,0x00,0x39,0xC0,0XE7,0x02,0xFF,0xFF};              
static char jd9366_video_on_cmd7[] = {0x02,0x00,0x39,0xC0,0XE0,0x01,0xFF,0xFF};
static char jd9366_video_on_cmd8[] = {0x02,0x00,0x39,0xC0,0X00,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd9[] = {0x02,0x00,0x39,0xC0,0X01,0xB7,0xFF,0xFF};
static char jd9366_video_on_cmd10[] = {0x02,0x00,0x39,0xC0,0X17,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd11[] = {0x02,0x00,0x39,0xC0,0X18,0xB2,0xFF,0xFF};
static char jd9366_video_on_cmd12[] = {0x02,0x00,0x39,0xC0,0X19,0x01,0xFF,0xFF};
static char jd9366_video_on_cmd13[] = {0x02,0x00,0x39,0xC0,0X1A,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd14[] = {0x02,0x00,0x39,0xC0,0X1B,0xB2,0xFF,0xFF};
static char jd9366_video_on_cmd15[] = {0x02,0x00,0x39,0xC0,0X1C,0x01,0xFF,0xFF};               
static char jd9366_video_on_cmd16[] = {0x02,0x00,0x39,0xC0,0X1F,0x7E,0xFF,0xFF};
static char jd9366_video_on_cmd17[] = {0x02,0x00,0x39,0xC0,0X20,0x28,0xFF,0xFF};
static char jd9366_video_on_cmd18[] = {0x02,0x00,0x39,0xC0,0X21,0x28,0xFF,0xFF};
static char jd9366_video_on_cmd19[] = {0x02,0x00,0x39,0xC0,0X22,0x0E,0xFF,0xFF};                        
static char jd9366_video_on_cmd20[] = {0x02,0x00,0x39,0xC0,0X24,0xC8,0xFF,0xFF};                      
static char jd9366_video_on_cmd21[] = {0x02,0x00,0x39,0xC0,0X37,0x29,0xFF,0xFF};
static char jd9366_video_on_cmd22[] = {0x02,0x00,0x39,0xC0,0X38,0x05,0xFF,0xFF};
static char jd9366_video_on_cmd23[] = {0x02,0x00,0x39,0xC0,0X39,0x08,0xFF,0xFF};
static char jd9366_video_on_cmd24[] = {0x02,0x00,0x39,0xC0,0X3A,0x12,0xFF,0xFF};
static char jd9366_video_on_cmd25[] = {0x02,0x00,0x39,0xC0,0X3C,0x78,0xFF,0xFF};
static char jd9366_video_on_cmd26[] = {0x02,0x00,0x39,0xC0,0X3E,0xFF,0xFF,0xFF};
static char jd9366_video_on_cmd27[] = {0x02,0x00,0x39,0xC0,0X3E,0xFF,0xFF,0xFF};
static char jd9366_video_on_cmd28[] = {0x02,0x00,0x39,0xC0,0X3F,0xFF,0xFF,0xFF};                       
static char jd9366_video_on_cmd29[] = {0x02,0x00,0x39,0xC0,0X40,0x06,0xFF,0xFF};
static char jd9366_video_on_cmd30[] = {0x02,0x00,0x39,0xC0,0X41,0xA0,0xFF,0xFF};
static char jd9366_video_on_cmd31[] = {0x02,0x00,0x39,0xC0,0X43,0x08,0xFF,0xFF};
static char jd9366_video_on_cmd32[] = {0x02,0x00,0x39,0xC0,0X44,0x07,0xFF,0xFF};
static char jd9366_video_on_cmd33[] = {0x02,0x00,0x39,0xC0,0X45,0x24,0xFF,0xFF};       
static char jd9366_video_on_cmd34[] = {0x02,0x00,0x39,0xC0,0x55,0x01,0xFF,0xFF};  
static char jd9366_video_on_cmd35[] = {0x02,0x00,0x39,0xC0,0x56,0x01,0xFF,0xFF};  
static char jd9366_video_on_cmd36[] = {0x02,0x00,0x39,0xC0,0x57,0x8D,0xFF,0xFF};  
static char jd9366_video_on_cmd37[] = {0x02,0x00,0x39,0xC0,0x58,0x0A,0xFF,0xFF};  
static char jd9366_video_on_cmd38[] = {0x02,0x00,0x39,0xC0,0x59,0x2A,0xFF,0xFF};  
static char jd9366_video_on_cmd39[] = {0x02,0x00,0x39,0xC0,0x5A,0x2A,0xFF,0xFF};  
static char jd9366_video_on_cmd40[] = {0x02,0x00,0x39,0xC0,0x5B,0x1E,0xFF,0xFF};                
static char jd9366_video_on_cmd41[] = {0x02,0x00,0x39,0xC0,0X5D,0x7C,0xFF,0xFF};
static char jd9366_video_on_cmd42[] = {0x02,0x00,0x39,0xC0,0X5E,0x59,0xFF,0xFF};
static char jd9366_video_on_cmd43[] = {0x02,0x00,0x39,0xC0,0X5F,0x47,0xFF,0xFF};
static char jd9366_video_on_cmd44[] = {0x02,0x00,0x39,0xC0,0X60,0x39,0xFF,0xFF};
static char jd9366_video_on_cmd45[] = {0x02,0x00,0x39,0xC0,0X61,0x33,0xFF,0xFF};
static char jd9366_video_on_cmd46[] = {0x02,0x00,0x39,0xC0,0X62,0x23,0xFF,0xFF};
static char jd9366_video_on_cmd47[] = {0x02,0x00,0x39,0xC0,0X63,0x27,0xFF,0xFF};
static char jd9366_video_on_cmd48[] = {0x02,0x00,0x39,0xC0,0X64,0x10,0xFF,0xFF};
static char jd9366_video_on_cmd49[] = {0x02,0x00,0x39,0xC0,0X65,0x27,0xFF,0xFF};
static char jd9366_video_on_cmd50[] = {0x02,0x00,0x39,0xC0,0X66,0x25,0xFF,0xFF};
static char jd9366_video_on_cmd51[] = {0x02,0x00,0x39,0xC0,0X67,0x23,0xFF,0xFF};
static char jd9366_video_on_cmd52[] = {0x02,0x00,0x39,0xC0,0X68,0x3F,0xFF,0xFF};
static char jd9366_video_on_cmd53[] = {0x02,0x00,0x39,0xC0,0X69,0x2C,0xFF,0xFF};
static char jd9366_video_on_cmd54[] = {0x02,0x00,0x39,0xC0,0X6A,0x33,0xFF,0xFF};
static char jd9366_video_on_cmd55[] = {0x02,0x00,0x39,0xC0,0X6B,0x25,0xFF,0xFF};
static char jd9366_video_on_cmd56[] = {0x02,0x00,0x39,0xC0,0X6C,0x23,0xFF,0xFF};
static char jd9366_video_on_cmd57[] = {0x02,0x00,0x39,0xC0,0X6D,0x17,0xFF,0xFF};
static char jd9366_video_on_cmd58[] = {0x02,0x00,0x39,0xC0,0X6E,0x0A,0xFF,0xFF};
static char jd9366_video_on_cmd59[] = {0x02,0x00,0x39,0xC0,0X6F,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd60[] = {0x02,0x00,0x39,0xC0,0X70,0x7C,0xFF,0xFF};
static char jd9366_video_on_cmd61[] = {0x02,0x00,0x39,0xC0,0X71,0x59,0xFF,0xFF};
static char jd9366_video_on_cmd62[] = {0x02,0x00,0x39,0xC0,0X72,0x47,0xFF,0xFF};
static char jd9366_video_on_cmd63[] = {0x02,0x00,0x39,0xC0,0X73,0x39,0xFF,0xFF};
static char jd9366_video_on_cmd64[] = {0x02,0x00,0x39,0xC0,0X74,0x33,0xFF,0xFF};
static char jd9366_video_on_cmd65[] = {0x02,0x00,0x39,0xC0,0X75,0x23,0xFF,0xFF};
static char jd9366_video_on_cmd66[] = {0x02,0x00,0x39,0xC0,0X76,0x27,0xFF,0xFF};
static char jd9366_video_on_cmd67[] = {0x02,0x00,0x39,0xC0,0X77,0x10,0xFF,0xFF};
static char jd9366_video_on_cmd68[] = {0x02,0x00,0x39,0xC0,0X78,0x27,0xFF,0xFF};
static char jd9366_video_on_cmd69[] = {0x02,0x00,0x39,0xC0,0X79,0x25,0xFF,0xFF};
static char jd9366_video_on_cmd70[] = {0x02,0x00,0x39,0xC0,0X7A,0x23,0xFF,0xFF};
static char jd9366_video_on_cmd71[] = {0x02,0x00,0x39,0xC0,0X7B,0x3F,0xFF,0xFF};
static char jd9366_video_on_cmd72[] = {0x02,0x00,0x39,0xC0,0X7C,0x2C,0xFF,0xFF};
static char jd9366_video_on_cmd73[] = {0x02,0x00,0x39,0xC0,0X7D,0x33,0xFF,0xFF};
static char jd9366_video_on_cmd74[] = {0x02,0x00,0x39,0xC0,0X7E,0x25,0xFF,0xFF};
static char jd9366_video_on_cmd75[] = {0x02,0x00,0x39,0xC0,0X7F,0x23,0xFF,0xFF};
static char jd9366_video_on_cmd76[] = {0x02,0x00,0x39,0xC0,0X80,0x17,0xFF,0xFF};
static char jd9366_video_on_cmd77[] = {0x02,0x00,0x39,0xC0,0X81,0x0A,0xFF,0xFF};
static char jd9366_video_on_cmd78[] = {0x02,0x00,0x39,0xC0,0X82,0x00,0xFF,0xFF};               
static char jd9366_video_on_cmd79[] = {0x02,0x00,0x39,0xC0,0XE0,0x02,0xFF,0xFF};              
static char jd9366_video_on_cmd80[] = {0x02,0x00,0x39,0xC0,0X00,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd81[] = {0x02,0x00,0x39,0xC0,0X01,0x04,0xFF,0xFF};
static char jd9366_video_on_cmd82[] = {0x02,0x00,0x39,0xC0,0X02,0x08,0xFF,0xFF};
static char jd9366_video_on_cmd83[] = {0x02,0x00,0x39,0xC0,0X03,0x05,0xFF,0xFF};
static char jd9366_video_on_cmd84[] = {0x02,0x00,0x39,0xC0,0X04,0x09,0xFF,0xFF};
static char jd9366_video_on_cmd85[] = {0x02,0x00,0x39,0xC0,0X05,0x06,0xFF,0xFF};
static char jd9366_video_on_cmd86[] = {0x02,0x00,0x39,0xC0,0X06,0x0A,0xFF,0xFF};
static char jd9366_video_on_cmd87[] = {0x02,0x00,0x39,0xC0,0X07,0x07,0xFF,0xFF};
static char jd9366_video_on_cmd88[] = {0x02,0x00,0x39,0xC0,0X08,0x0B,0xFF,0xFF};
static char jd9366_video_on_cmd89[] = {0x02,0x00,0x39,0xC0,0X09,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd90[] = {0x02,0x00,0x39,0xC0,0X0A,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd91[] = {0x02,0x00,0x39,0xC0,0X0B,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd92[] = {0x02,0x00,0x39,0xC0,0X0C,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd93[] = {0x02,0x00,0x39,0xC0,0X0D,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd94[] = {0x02,0x00,0x39,0xC0,0X0E,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd95[] = {0x02,0x00,0x39,0xC0,0X0F,0x17,0xFF,0xFF};
static char jd9366_video_on_cmd96[] = {0x02,0x00,0x39,0xC0,0X10,0x37,0xFF,0xFF};
static char jd9366_video_on_cmd97[] = {0x02,0x00,0x39,0xC0,0X11,0x10,0xFF,0xFF};
static char jd9366_video_on_cmd98[] = {0x02,0x00,0x39,0xC0,0X12,0x1F,0xFF,0xFF};
static char jd9366_video_on_cmd99[] = {0x02,0x00,0x39,0xC0,0X13,0x1F,0xFF,0xFF};
static char jd9366_video_on_cmd100[] = {0x02,0x00,0x39,0xC0,0X14,0x1F,0xFF,0xFF};
static char jd9366_video_on_cmd101[] = {0x02,0x00,0x39,0xC0,0X15,0x1F,0xFF,0xFF};              
static char jd9366_video_on_cmd102[] = {0x02,0x00,0x39,0xC0,0X16,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd103[] = {0x02,0x00,0x39,0xC0,0X17,0x04,0xFF,0xFF};
static char jd9366_video_on_cmd104[] = {0x02,0x00,0x39,0xC0,0X18,0x08,0xFF,0xFF};
static char jd9366_video_on_cmd105[] = {0x02,0x00,0x39,0xC0,0X19,0x05,0xFF,0xFF};
static char jd9366_video_on_cmd106[] = {0x02,0x00,0x39,0xC0,0X1A,0x09,0xFF,0xFF};
static char jd9366_video_on_cmd107[] = {0x02,0x00,0x39,0xC0,0X1B,0x06,0xFF,0xFF};
static char jd9366_video_on_cmd108[] = {0x02,0x00,0x39,0xC0,0X1C,0x0A,0xFF,0xFF};
static char jd9366_video_on_cmd109[] = {0x02,0x00,0x39,0xC0,0X1D,0x07,0xFF,0xFF};
static char jd9366_video_on_cmd110[] = {0x02,0x00,0x39,0xC0,0X1E,0x0B,0xFF,0xFF};
static char jd9366_video_on_cmd111[] = {0x02,0x00,0x39,0xC0,0X1F,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd112[] = {0x02,0x00,0x39,0xC0,0X20,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd113[] = {0x02,0x00,0x39,0xC0,0X21,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd114[] = {0x02,0x00,0x39,0xC0,0X22,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd115[] = {0x02,0x00,0x39,0xC0,0X23,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd116[] = {0x02,0x00,0x39,0xC0,0X24,0x1f,0xFF,0xFF};
static char jd9366_video_on_cmd117[] = {0x02,0x00,0x39,0xC0,0X25,0x17,0xFF,0xFF};
static char jd9366_video_on_cmd118[] = {0x02,0x00,0x39,0xC0,0X26,0x37,0xFF,0xFF};
static char jd9366_video_on_cmd119[] = {0x02,0x00,0x39,0xC0,0X27,0x10,0xFF,0xFF};
static char jd9366_video_on_cmd120[] = {0x02,0x00,0x39,0xC0,0X28,0x1F,0xFF,0xFF};
static char jd9366_video_on_cmd121[] = {0x02,0x00,0x39,0xC0,0X29,0x1F,0xFF,0xFF};
static char jd9366_video_on_cmd122[] = {0x02,0x00,0x39,0xC0,0X2A,0x1F,0xFF,0xFF};
static char jd9366_video_on_cmd123[] = {0x02,0x00,0x39,0xC0,0X2B,0x1F,0xFF,0xFF};                      
static char jd9366_video_on_cmd124[] = {0x02,0x00,0x39,0xC0,0X58,0x01,0xFF,0xFF};
static char jd9366_video_on_cmd125[] = {0x02,0x00,0x39,0xC0,0X59,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd126[] = {0x02,0x00,0x39,0xC0,0X5A,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd127[] = {0x02,0x00,0x39,0xC0,0X5B,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd128[] = {0x02,0x00,0x39,0xC0,0X5C,0x01,0xFF,0xFF};
static char jd9366_video_on_cmd129[] = {0x02,0x00,0x39,0xC0,0X5D,0x30,0xFF,0xFF};
static char jd9366_video_on_cmd130[] = {0x02,0x00,0x39,0xC0,0X5E,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd131[] = {0x02,0x00,0x39,0xC0,0X5F,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd132[] = {0x02,0x00,0x39,0xC0,0X60,0x30,0xFF,0xFF};
static char jd9366_video_on_cmd133[] = {0x02,0x00,0x39,0xC0,0X61,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd134[] = {0x02,0x00,0x39,0xC0,0X62,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd135[] = {0x02,0x00,0x39,0xC0,0X63,0x03,0xFF,0xFF};
static char jd9366_video_on_cmd136[] = {0x02,0x00,0x39,0xC0,0X64,0x6A,0xFF,0xFF};
static char jd9366_video_on_cmd137[] = {0x02,0x00,0x39,0xC0,0X65,0x45,0xFF,0xFF};
static char jd9366_video_on_cmd138[] = {0x02,0x00,0x39,0xC0,0X66,0x08,0xFF,0xFF};
static char jd9366_video_on_cmd139[] = {0x02,0x00,0x39,0xC0,0X67,0x73,0xFF,0xFF};
static char jd9366_video_on_cmd140[] = {0x02,0x00,0x39,0xC0,0X68,0x05,0xFF,0xFF};
static char jd9366_video_on_cmd141[] = {0x02,0x00,0x39,0xC0,0X69,0x06,0xFF,0xFF};
static char jd9366_video_on_cmd142[] = {0x02,0x00,0x39,0xC0,0X6A,0x6A,0xFF,0xFF};
static char jd9366_video_on_cmd143[] = {0x02,0x00,0x39,0xC0,0X6B,0x08,0xFF,0xFF};
static char jd9366_video_on_cmd144[] = {0x02,0x00,0x39,0xC0,0X6C,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd145[] = {0x02,0x00,0x39,0xC0,0X6D,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd146[] = {0x02,0x00,0x39,0xC0,0X6E,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd147[] = {0x02,0x00,0x39,0xC0,0X6F,0x88,0xFF,0xFF};
static char jd9366_video_on_cmd148[] = {0x02,0x00,0x39,0xC0,0X70,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd149[] = {0x02,0x00,0x39,0xC0,0X71,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd150[] = {0x02,0x00,0x39,0xC0,0X72,0x06,0xFF,0xFF};
static char jd9366_video_on_cmd151[] = {0x02,0x00,0x39,0xC0,0X73,0x7B,0xFF,0xFF};
static char jd9366_video_on_cmd152[] = {0x02,0x00,0x39,0xC0,0X74,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd153[] = {0x02,0x00,0x39,0xC0,0X75,0x80,0xFF,0xFF};
static char jd9366_video_on_cmd154[] = {0x02,0x00,0x39,0xC0,0X76,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd155[] = {0x02,0x00,0x39,0xC0,0X77,0x05,0xFF,0xFF};
static char jd9366_video_on_cmd156[] = {0x02,0x00,0x39,0xC0,0X78,0x10,0xFF,0xFF};
static char jd9366_video_on_cmd157[] = {0x02,0x00,0x39,0xC0,0X79,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd158[] = {0x02,0x00,0x39,0xC0,0X7A,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd159[] = {0x02,0x00,0x39,0xC0,0X7B,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd160[] = {0x02,0x00,0x39,0xC0,0X7C,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd161[] = {0x02,0x00,0x39,0xC0,0X7D,0x03,0xFF,0xFF};
static char jd9366_video_on_cmd162[] = {0x02,0x00,0x39,0xC0,0X7E,0x7B,0xFF,0xFF};                            
static char jd9366_video_on_cmd163[] = {0x02,0x00,0x39,0xC0,0XE0,0x01,0xFF,0xFF};
static char jd9366_video_on_cmd164[] = {0x02,0x00,0x39,0xC0,0X0E,0x01,0xFF,0xFF};                          
static char jd9366_video_on_cmd165[] = {0x02,0x00,0x39,0xC0,0XE0,0x03,0xFF,0xFF};
static char jd9366_video_on_cmd166[] = {0x02,0x00,0x39,0xC0,0X98,0x2F,0xFF,0xFF};                          
static char jd9366_video_on_cmd167[] = {0x02,0x00,0x39,0xC0,0XE0,0x04,0xFF,0xFF};
static char jd9366_video_on_cmd168[] = {0x02,0x00,0x39,0xC0,0X2B,0x2B,0xFF,0xFF};
static char jd9366_video_on_cmd169[] = {0x02,0x00,0x39,0xC0,0X2E,0x44,0xFF,0xFF};                         
static char jd9366_video_on_cmd170[] = {0x02,0x00,0x39,0xC0,0XE0,0x00,0xFF,0xFF};
static char jd9366_video_on_cmd171[] = {0x02,0x00,0x39,0xC0,0X35,0x00,0xFF,0xFF};


static char jd9366_video_on_exit_sleep[] = {
	0x11, 0x00, 0x05, 0x80
};

static char jd9366_video_on_display_on[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd jd9366_video_on_command[] = {
{ARRAY_SIZE(jd9366_video_on_cmd1), jd9366_video_on_cmd1, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd2), jd9366_video_on_cmd2, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd3), jd9366_video_on_cmd3, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd4), jd9366_video_on_cmd4, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd5), jd9366_video_on_cmd5, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd6), jd9366_video_on_cmd6, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd7), jd9366_video_on_cmd7, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd8), jd9366_video_on_cmd8, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd9), jd9366_video_on_cmd9, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd10), jd9366_video_on_cmd10, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd11), jd9366_video_on_cmd11, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd12), jd9366_video_on_cmd12, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd13), jd9366_video_on_cmd13, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd14), jd9366_video_on_cmd14, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd15), jd9366_video_on_cmd15, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd16), jd9366_video_on_cmd16, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd17), jd9366_video_on_cmd17, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd18), jd9366_video_on_cmd18, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd19), jd9366_video_on_cmd19, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd20), jd9366_video_on_cmd20, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd21), jd9366_video_on_cmd21, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd22), jd9366_video_on_cmd22, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd23), jd9366_video_on_cmd23, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd24), jd9366_video_on_cmd24, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd25), jd9366_video_on_cmd25, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd26), jd9366_video_on_cmd26, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd27), jd9366_video_on_cmd27, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd28), jd9366_video_on_cmd28, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd29), jd9366_video_on_cmd29, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd30), jd9366_video_on_cmd30, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd31), jd9366_video_on_cmd31, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd32), jd9366_video_on_cmd32, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd33), jd9366_video_on_cmd33, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd34), jd9366_video_on_cmd34, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd35), jd9366_video_on_cmd35, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd36), jd9366_video_on_cmd36, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd37), jd9366_video_on_cmd37, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd38), jd9366_video_on_cmd38, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd39), jd9366_video_on_cmd39, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd40), jd9366_video_on_cmd40, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd41), jd9366_video_on_cmd41, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd42), jd9366_video_on_cmd42, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd43), jd9366_video_on_cmd43, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd44), jd9366_video_on_cmd44, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd45), jd9366_video_on_cmd45, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd46), jd9366_video_on_cmd46, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd47), jd9366_video_on_cmd47, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd48), jd9366_video_on_cmd48, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd49), jd9366_video_on_cmd49, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd50), jd9366_video_on_cmd50, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd51), jd9366_video_on_cmd51, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd52), jd9366_video_on_cmd52, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd53), jd9366_video_on_cmd53, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd54), jd9366_video_on_cmd54, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd55), jd9366_video_on_cmd55, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd56), jd9366_video_on_cmd56, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd57), jd9366_video_on_cmd57, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd58), jd9366_video_on_cmd58, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd59), jd9366_video_on_cmd59, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd60), jd9366_video_on_cmd60, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd61), jd9366_video_on_cmd61, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd62), jd9366_video_on_cmd62, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd63), jd9366_video_on_cmd63, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd64), jd9366_video_on_cmd64, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd65), jd9366_video_on_cmd65, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd66), jd9366_video_on_cmd66, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd67), jd9366_video_on_cmd67, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd68), jd9366_video_on_cmd68, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd69), jd9366_video_on_cmd69, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd70), jd9366_video_on_cmd70, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd71), jd9366_video_on_cmd71, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd72), jd9366_video_on_cmd72, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd73), jd9366_video_on_cmd73, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd74), jd9366_video_on_cmd74, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd75), jd9366_video_on_cmd75, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd76), jd9366_video_on_cmd76, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd77), jd9366_video_on_cmd77, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd78), jd9366_video_on_cmd78, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd79), jd9366_video_on_cmd79, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd80), jd9366_video_on_cmd80, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd81), jd9366_video_on_cmd81, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd82), jd9366_video_on_cmd82, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd83), jd9366_video_on_cmd83, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd84), jd9366_video_on_cmd84, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd85), jd9366_video_on_cmd85, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd86), jd9366_video_on_cmd86, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd87), jd9366_video_on_cmd87, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd88), jd9366_video_on_cmd88, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd89), jd9366_video_on_cmd89, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd90), jd9366_video_on_cmd90, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd91), jd9366_video_on_cmd91, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd92), jd9366_video_on_cmd92, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd93), jd9366_video_on_cmd93, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd94), jd9366_video_on_cmd94, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd95), jd9366_video_on_cmd95, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd96), jd9366_video_on_cmd96, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd97), jd9366_video_on_cmd97, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd98), jd9366_video_on_cmd98, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd99), jd9366_video_on_cmd99, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd100), jd9366_video_on_cmd100, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd101), jd9366_video_on_cmd101, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd102), jd9366_video_on_cmd102, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd103), jd9366_video_on_cmd103, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd104), jd9366_video_on_cmd104, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd105), jd9366_video_on_cmd105, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd106), jd9366_video_on_cmd106, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd107), jd9366_video_on_cmd107, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd108), jd9366_video_on_cmd108, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd109), jd9366_video_on_cmd109, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd110), jd9366_video_on_cmd110, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd111), jd9366_video_on_cmd111, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd112), jd9366_video_on_cmd112, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd113), jd9366_video_on_cmd113, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd114), jd9366_video_on_cmd114, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd115), jd9366_video_on_cmd115, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd116), jd9366_video_on_cmd116, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd117), jd9366_video_on_cmd117, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd118), jd9366_video_on_cmd118, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd119), jd9366_video_on_cmd119, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd120), jd9366_video_on_cmd120, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd121), jd9366_video_on_cmd121, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd122), jd9366_video_on_cmd122, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd123), jd9366_video_on_cmd123, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd124), jd9366_video_on_cmd124, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd125), jd9366_video_on_cmd125, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd126), jd9366_video_on_cmd126, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd127), jd9366_video_on_cmd127, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd128), jd9366_video_on_cmd128, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd129), jd9366_video_on_cmd129, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd130), jd9366_video_on_cmd130, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd131), jd9366_video_on_cmd131, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd132), jd9366_video_on_cmd132, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd133), jd9366_video_on_cmd133, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd134), jd9366_video_on_cmd134, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd135), jd9366_video_on_cmd135, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd136), jd9366_video_on_cmd136, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd137), jd9366_video_on_cmd137, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd138), jd9366_video_on_cmd138, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd139), jd9366_video_on_cmd139, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd140), jd9366_video_on_cmd140, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd141), jd9366_video_on_cmd141, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd142), jd9366_video_on_cmd142, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd143), jd9366_video_on_cmd143, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd144), jd9366_video_on_cmd144, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd145), jd9366_video_on_cmd145, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd146), jd9366_video_on_cmd146, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd147), jd9366_video_on_cmd147, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd148), jd9366_video_on_cmd148, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd149), jd9366_video_on_cmd149, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd150), jd9366_video_on_cmd150, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd151), jd9366_video_on_cmd151, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd152), jd9366_video_on_cmd152, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd153), jd9366_video_on_cmd153, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd154), jd9366_video_on_cmd154, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd155), jd9366_video_on_cmd155, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd156), jd9366_video_on_cmd156, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd157), jd9366_video_on_cmd157, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd158), jd9366_video_on_cmd158, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd159), jd9366_video_on_cmd159, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd160), jd9366_video_on_cmd160, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd161), jd9366_video_on_cmd161, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd162), jd9366_video_on_cmd162, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd163), jd9366_video_on_cmd163, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd164), jd9366_video_on_cmd164, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd165), jd9366_video_on_cmd165, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd166), jd9366_video_on_cmd166, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd167), jd9366_video_on_cmd167, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd168), jd9366_video_on_cmd168, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd169), jd9366_video_on_cmd169, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd170), jd9366_video_on_cmd170, 0x01},
{ARRAY_SIZE(jd9366_video_on_cmd171), jd9366_video_on_cmd171, 0x01},
{ARRAY_SIZE(jd9366_video_on_exit_sleep), jd9366_video_on_exit_sleep, 0x78},
{ARRAY_SIZE(jd9366_video_on_display_on), jd9366_video_on_display_on, 0x14},
};

#define JD9366_VIDEO_ON_COMMAND 173


static char jd9366_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char jd9366_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd jd9366_video_off_command[] = {
	{0x4, jd9366_videooff_cmd0, 0x32},
	{0x4, jd9366_videooff_cmd1, 0x78}
};

#define JD9366_VIDEO_OFF_COMMAND 2


static struct command_state jd9366_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info jd9366_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info jd9366_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration jd9366_video_lane_config = {
	4, 0, 1, 1, 1, 1, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t jd9366_video_timings[] = {
	0x86, 0x1E, 0x14, 0x00, 0x43, 0x4B, 0x19, 0x21, 0x22, 0x03, 0x04, 0x00
};

static const uint32_t jd9366_14nm_video_timings[] = {
	0x31, 0x2A, 0x11, 0x14, 0x0D, 0x03, 0x04, 0xa0,
	0x31, 0x2A, 0x11, 0x14, 0x0D, 0x03, 0x04, 0xa0,
	0x31, 0x2A, 0x11, 0x14, 0x0D, 0x03, 0x04, 0xa0,
	0x31, 0x2A, 0x11, 0x14, 0x0D, 0x03, 0x04, 0xa0,
	0x31, 0x3E, 0x11, 0x14, 0x0D, 0x03, 0x04, 0xa0,
};

static struct panel_timing jd9366_video_timing_info = {
	0, 4, 0x04, 0x1D
};

static struct labibb_desc jd9366_video_labibb = {
	0, 1, 5700000, 5700000, 5700000, 5700000, 3, 3, 1, 0
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence jd9366_video_reset_seq = {
	{1, 0, 1, }, {20, 50, 100, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
/*static struct backlight jd9366_video_backlight = {
	0, 1, 255, 0, 0, 0
};*/

static struct backlight jd9366_video_backlight = {
	1, 1, 4095, 100, 1, "PMIC_8941"
};

#define JD9366_VIDEO_SIGNATURE 0xFFFF

#endif /*_PANEL_JD9366_VIDEO_H_*/


