/* Copyright (c) 2014, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_JD9366_NEW_VIDEO_H_
#define _PANEL_JD9366_NEW_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config jd9366_new_video_panel_data = {
	"qcom,mdss_dsi_jd9366_new_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution jd9366_new_video_panel_res = {
	800, 1280, 32, 20, 20, 0, 8, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info jd9366_new_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char jd9366_new_video_on_cmd1[] =   {0x02,0x00,0x39,0xC0,0xE0,0x00,0xFF,0xFF};         
static char jd9366_new_video_on_cmd2[] =   {0x02,0x00,0x39,0xC0,0xE1,0x93,0xFF,0xFF};
static char jd9366_new_video_on_cmd3[] =   {0x02,0x00,0x39,0xC0,0xE2,0x65,0xFF,0xFF};
static char jd9366_new_video_on_cmd4[] =   {0x02,0x00,0x39,0xC0,0xE3,0xF8,0xFF,0xFF};                            
static char jd9366_new_video_on_cmd5[] =   {0x02,0x00,0x39,0xC0,0x80,0x03,0xFF,0xFF};
static char jd9366_new_video_on_cmd6[] =   {0x02,0x00,0x39,0xC0,0xE0,0x01,0xFF,0xFF};              
static char jd9366_new_video_on_cmd7[] =   {0x02,0x00,0x39,0xC0,0x00,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd8[] =   {0x02,0x00,0x39,0xC0,0x01,0xA0,0xFF,0xFF};
static char jd9366_new_video_on_cmd9[] =   {0x02,0x00,0x39,0xC0,0x03,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd10[] =  {0x02,0x00,0x39,0xC0,0x04,0xA0,0xFF,0xFF};
static char jd9366_new_video_on_cmd11[] =  {0x02,0x00,0x39,0xC0,0x17,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd12[] =  {0x02,0x00,0x39,0xC0,0x18,0xB1,0xFF,0xFF};
static char jd9366_new_video_on_cmd13[] =  {0x02,0x00,0x39,0xC0,0x19,0x01,0xFF,0xFF};
static char jd9366_new_video_on_cmd14[] =  {0x02,0x00,0x39,0xC0,0x1A,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd15[] =  {0x02,0x00,0x39,0xC0,0x1B,0xB1,0xFF,0xFF};               
static char jd9366_new_video_on_cmd16[] =  {0x02,0x00,0x39,0xC0,0x1C,0x01,0xFF,0xFF};
static char jd9366_new_video_on_cmd17[] =  {0x02,0x00,0x39,0xC0,0x1F,0x3E,0xFF,0xFF};
static char jd9366_new_video_on_cmd18[] =  {0x02,0x00,0x39,0xC0,0x20,0x28,0xFF,0xFF};
static char jd9366_new_video_on_cmd19[] =  {0x02,0x00,0x39,0xC0,0x21,0x28,0xFF,0xFF};                        
static char jd9366_new_video_on_cmd20[] =  {0x02,0x00,0x39,0xC0,0x22,0x0E,0xFF,0xFF};                      
static char jd9366_new_video_on_cmd21[] =  {0x02,0x00,0x39,0xC0,0x37,0x19,0xFF,0xFF};
static char jd9366_new_video_on_cmd22[] =  {0x02,0x00,0x39,0xC0,0x38,0x05,0xFF,0xFF};
static char jd9366_new_video_on_cmd23[] =  {0x02,0x00,0x39,0xC0,0x39,0x08,0xFF,0xFF};
static char jd9366_new_video_on_cmd24[] =  {0x02,0x00,0x39,0xC0,0x3A,0x12,0xFF,0xFF};
static char jd9366_new_video_on_cmd25[] =  {0x02,0x00,0x39,0xC0,0x3C,0x78,0xFF,0xFF};
static char jd9366_new_video_on_cmd26[] =  {0x02,0x00,0x39,0xC0,0x3D,0xFF,0xFF,0xFF};
static char jd9366_new_video_on_cmd27[] =  {0x02,0x00,0x39,0xC0,0x3E,0xFF,0xFF,0xFF};
static char jd9366_new_video_on_cmd28[] =  {0x02,0x00,0x39,0xC0,0x3F,0xFF,0xFF,0xFF};                       
static char jd9366_new_video_on_cmd29[] =  {0x02,0x00,0x39,0xC0,0x40,0x06,0xFF,0xFF};
static char jd9366_new_video_on_cmd30[] =  {0x02,0x00,0x39,0xC0,0x41,0xA0,0xFF,0xFF};
static char jd9366_new_video_on_cmd31[] =  {0x02,0x00,0x39,0xC0,0x43,0x08,0xFF,0xFF};
static char jd9366_new_video_on_cmd32[] =  {0x02,0x00,0x39,0xC0,0x44,0x07,0xFF,0xFF};
static char jd9366_new_video_on_cmd33[] =  {0x02,0x00,0x39,0xC0,0x45,0x40,0xFF,0xFF};       
static char jd9366_new_video_on_cmd34[] =  {0x02,0x00,0x39,0xC0,0x4B,0x04,0xFF,0xFF};  
static char jd9366_new_video_on_cmd35[] =  {0x02,0x00,0x39,0xC0,0x55,0x01,0xFF,0xFF};  
static char jd9366_new_video_on_cmd36[] =  {0x02,0x00,0x39,0xC0,0x56,0x01,0xFF,0xFF};  
static char jd9366_new_video_on_cmd37[] =  {0x02,0x00,0x39,0xC0,0x57,0x89,0xFF,0xFF};  
static char jd9366_new_video_on_cmd38[] =  {0x02,0x00,0x39,0xC0,0x58,0x0A,0xFF,0xFF};  
static char jd9366_new_video_on_cmd39[] =  {0x02,0x00,0x39,0xC0,0x59,0x0A,0xFF,0xFF};  
static char jd9366_new_video_on_cmd40[] =  {0x02,0x00,0x39,0xC0,0x5A,0x28,0xFF,0xFF};                
static char jd9366_new_video_on_cmd41[] =  {0x02,0x00,0x39,0xC0,0x5B,0x14,0xFF,0xFF};
static char jd9366_new_video_on_cmd42[] =  {0x02,0x00,0x39,0xC0,0x5D,0x7C,0xFF,0xFF};
static char jd9366_new_video_on_cmd43[] =  {0x02,0x00,0x39,0xC0,0x5E,0x66,0xFF,0xFF};
static char jd9366_new_video_on_cmd44[] =  {0x02,0x00,0x39,0xC0,0x5F,0x57,0xFF,0xFF};
static char jd9366_new_video_on_cmd45[] =  {0x02,0x00,0x39,0xC0,0x60,0x49,0xFF,0xFF};
static char jd9366_new_video_on_cmd46[] =  {0x02,0x00,0x39,0xC0,0x61,0x46,0xFF,0xFF};
static char jd9366_new_video_on_cmd47[] =  {0x02,0x00,0x39,0xC0,0x62,0x38,0xFF,0xFF};
static char jd9366_new_video_on_cmd48[] =  {0x02,0x00,0x39,0xC0,0x63,0x3C,0xFF,0xFF};
static char jd9366_new_video_on_cmd49[] =  {0x02,0x00,0x39,0xC0,0x64,0x25,0xFF,0xFF};
static char jd9366_new_video_on_cmd50[] =  {0x02,0x00,0x39,0xC0,0x65,0x3E,0xFF,0xFF};
static char jd9366_new_video_on_cmd51[] =  {0x02,0x00,0x39,0xC0,0x66,0x3B,0xFF,0xFF};
static char jd9366_new_video_on_cmd52[] =  {0x02,0x00,0x39,0xC0,0x67,0x3A,0xFF,0xFF};
static char jd9366_new_video_on_cmd53[] =  {0x02,0x00,0x39,0xC0,0x68,0x55,0xFF,0xFF};
static char jd9366_new_video_on_cmd54[] =  {0x02,0x00,0x39,0xC0,0x69,0x40,0xFF,0xFF};
static char jd9366_new_video_on_cmd55[] =  {0x02,0x00,0x39,0xC0,0x6A,0x47,0xFF,0xFF};
static char jd9366_new_video_on_cmd56[] =  {0x02,0x00,0x39,0xC0,0x6B,0x38,0xFF,0xFF};
static char jd9366_new_video_on_cmd57[] =  {0x02,0x00,0x39,0xC0,0x6C,0x31,0xFF,0xFF};
static char jd9366_new_video_on_cmd58[] =  {0x02,0x00,0x39,0xC0,0x6D,0x22,0xFF,0xFF};
static char jd9366_new_video_on_cmd59[] =  {0x02,0x00,0x39,0xC0,0x6E,0x11,0xFF,0xFF};
static char jd9366_new_video_on_cmd60[] =  {0x02,0x00,0x39,0xC0,0x6F,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd61[] =  {0x02,0x00,0x39,0xC0,0x70,0x7C,0xFF,0xFF};
static char jd9366_new_video_on_cmd62[] =  {0x02,0x00,0x39,0xC0,0x71,0x66,0xFF,0xFF};
static char jd9366_new_video_on_cmd63[] =  {0x02,0x00,0x39,0xC0,0x72,0x57,0xFF,0xFF};
static char jd9366_new_video_on_cmd64[] =  {0x02,0x00,0x39,0xC0,0x73,0x49,0xFF,0xFF};
static char jd9366_new_video_on_cmd65[] =  {0x02,0x00,0x39,0xC0,0x74,0x46,0xFF,0xFF};
static char jd9366_new_video_on_cmd66[] =  {0x02,0x00,0x39,0xC0,0x75,0x38,0xFF,0xFF};
static char jd9366_new_video_on_cmd67[] =  {0x02,0x00,0x39,0xC0,0x76,0x3C,0xFF,0xFF};
static char jd9366_new_video_on_cmd68[] =  {0x02,0x00,0x39,0xC0,0x77,0x25,0xFF,0xFF};
static char jd9366_new_video_on_cmd69[] =  {0x02,0x00,0x39,0xC0,0x78,0x3E,0xFF,0xFF};
static char jd9366_new_video_on_cmd70[] =  {0x02,0x00,0x39,0xC0,0x79,0x3B,0xFF,0xFF};
static char jd9366_new_video_on_cmd71[] =  {0x02,0x00,0x39,0xC0,0x7A,0x3A,0xFF,0xFF};
static char jd9366_new_video_on_cmd72[] =  {0x02,0x00,0x39,0xC0,0x7B,0x55,0xFF,0xFF};
static char jd9366_new_video_on_cmd73[] =  {0x02,0x00,0x39,0xC0,0x7C,0x40,0xFF,0xFF};
static char jd9366_new_video_on_cmd74[] =  {0x02,0x00,0x39,0xC0,0x7D,0x47,0xFF,0xFF};
static char jd9366_new_video_on_cmd75[] =  {0x02,0x00,0x39,0xC0,0x7E,0x38,0xFF,0xFF};
static char jd9366_new_video_on_cmd76[] =  {0x02,0x00,0x39,0xC0,0x7F,0x31,0xFF,0xFF};
static char jd9366_new_video_on_cmd77[] =  {0x02,0x00,0x39,0xC0,0x80,0x22,0xFF,0xFF};
static char jd9366_new_video_on_cmd78[] =  {0x02,0x00,0x39,0xC0,0x81,0x11,0xFF,0xFF};               
static char jd9366_new_video_on_cmd79[] =  {0x02,0x00,0x39,0xC0,0x82,0x00,0xFF,0xFF};              
static char jd9366_new_video_on_cmd80[] =  {0x02,0x00,0x39,0xC0,0xE0,0x02,0xFF,0xFF};
static char jd9366_new_video_on_cmd81[] =  {0x02,0x00,0x39,0xC0,0x00,0x47,0xFF,0xFF};
static char jd9366_new_video_on_cmd82[] =  {0x02,0x00,0x39,0xC0,0x01,0x47,0xFF,0xFF};
static char jd9366_new_video_on_cmd83[] =  {0x02,0x00,0x39,0xC0,0x02,0x45,0xFF,0xFF};
static char jd9366_new_video_on_cmd84[] =  {0x02,0x00,0x39,0xC0,0x03,0x45,0xFF,0xFF};
static char jd9366_new_video_on_cmd85[] =  {0x02,0x00,0x39,0xC0,0x04,0x4B,0xFF,0xFF};
static char jd9366_new_video_on_cmd86[] =  {0x02,0x00,0x39,0xC0,0x05,0x4B,0xFF,0xFF};
static char jd9366_new_video_on_cmd87[] =  {0x02,0x00,0x39,0xC0,0x06,0x49,0xFF,0xFF};
static char jd9366_new_video_on_cmd88[] =  {0x02,0x00,0x39,0xC0,0x07,0x49,0xFF,0xFF};
static char jd9366_new_video_on_cmd89[] =  {0x02,0x00,0x39,0xC0,0x08,0x41,0xFF,0xFF};
static char jd9366_new_video_on_cmd90[] =  {0x02,0x00,0x39,0xC0,0x09,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd91[] =  {0x02,0x00,0x39,0xC0,0x0A,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd92[] =  {0x02,0x00,0x39,0xC0,0x0B,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd93[] =  {0x02,0x00,0x39,0xC0,0x0C,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd94[] =  {0x02,0x00,0x39,0xC0,0x0D,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd95[] =  {0x02,0x00,0x39,0xC0,0x0E,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd96[] =  {0x02,0x00,0x39,0xC0,0x0F,0x43,0xFF,0xFF};
static char jd9366_new_video_on_cmd97[] =  {0x02,0x00,0x39,0xC0,0x10,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd98[] =  {0x02,0x00,0x39,0xC0,0x11,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd99[] =  {0x02,0x00,0x39,0xC0,0x12,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd100[] = {0x02,0x00,0x39,0xC0,0x13,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd101[] = {0x02,0x00,0x39,0xC0,0x14,0x1F,0xFF,0xFF};              
static char jd9366_new_video_on_cmd102[] = {0x02,0x00,0x39,0xC0,0x15,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd103[] = {0x02,0x00,0x39,0xC0,0x16,0x46,0xFF,0xFF};
static char jd9366_new_video_on_cmd104[] = {0x02,0x00,0x39,0xC0,0x17,0x46,0xFF,0xFF};
static char jd9366_new_video_on_cmd105[] = {0x02,0x00,0x39,0xC0,0x18,0x44,0xFF,0xFF};
static char jd9366_new_video_on_cmd106[] = {0x02,0x00,0x39,0xC0,0x19,0x44,0xFF,0xFF};
static char jd9366_new_video_on_cmd107[] = {0x02,0x00,0x39,0xC0,0x1A,0x4A,0xFF,0xFF};
static char jd9366_new_video_on_cmd108[] = {0x02,0x00,0x39,0xC0,0x1B,0x4A,0xFF,0xFF};
static char jd9366_new_video_on_cmd109[] = {0x02,0x00,0x39,0xC0,0x1C,0x48,0xFF,0xFF};
static char jd9366_new_video_on_cmd110[] = {0x02,0x00,0x39,0xC0,0x1D,0x48,0xFF,0xFF};
static char jd9366_new_video_on_cmd111[] = {0x02,0x00,0x39,0xC0,0x1E,0x40,0xFF,0xFF};
static char jd9366_new_video_on_cmd112[] = {0x02,0x00,0x39,0xC0,0x1F,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd113[] = {0x02,0x00,0x39,0xC0,0x20,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd114[] = {0x02,0x00,0x39,0xC0,0x21,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd115[] = {0x02,0x00,0x39,0xC0,0x22,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd116[] = {0x02,0x00,0x39,0xC0,0x23,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd117[] = {0x02,0x00,0x39,0xC0,0x24,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd118[] = {0x02,0x00,0x39,0xC0,0x25,0x42,0xFF,0xFF};
static char jd9366_new_video_on_cmd119[] = {0x02,0x00,0x39,0xC0,0x26,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd120[] = {0x02,0x00,0x39,0xC0,0x27,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd121[] = {0x02,0x00,0x39,0xC0,0x28,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd122[] = {0x02,0x00,0x39,0xC0,0x29,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd123[] = {0x02,0x00,0x39,0xC0,0x2A,0x1F,0xFF,0xFF};                      
static char jd9366_new_video_on_cmd124[] = {0x02,0x00,0x39,0xC0,0x2B,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd125[] = {0x02,0x00,0x39,0xC0,0x2C,0x11,0xFF,0xFF};
static char jd9366_new_video_on_cmd126[] = {0x02,0x00,0x39,0xC0,0x2D,0x0F,0xFF,0xFF};
static char jd9366_new_video_on_cmd127[] = {0x02,0x00,0x39,0xC0,0x2E,0x0D,0xFF,0xFF};
static char jd9366_new_video_on_cmd128[] = {0x02,0x00,0x39,0xC0,0x2F,0x0B,0xFF,0xFF};
static char jd9366_new_video_on_cmd129[] = {0x02,0x00,0x39,0xC0,0x30,0x09,0xFF,0xFF};
static char jd9366_new_video_on_cmd130[] = {0x02,0x00,0x39,0xC0,0x31,0x07,0xFF,0xFF};
static char jd9366_new_video_on_cmd131[] = {0x02,0x00,0x39,0xC0,0x32,0x05,0xFF,0xFF};
static char jd9366_new_video_on_cmd132[] = {0x02,0x00,0x39,0xC0,0x33,0x18,0xFF,0xFF};
static char jd9366_new_video_on_cmd133[] = {0x02,0x00,0x39,0xC0,0x34,0x17,0xFF,0xFF};
static char jd9366_new_video_on_cmd134[] = {0x02,0x00,0x39,0xC0,0x35,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd135[] = {0x02,0x00,0x39,0xC0,0x36,0x01,0xFF,0xFF};
static char jd9366_new_video_on_cmd136[] = {0x02,0x00,0x39,0xC0,0x37,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd137[] = {0x02,0x00,0x39,0xC0,0x38,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd138[] = {0x02,0x00,0x39,0xC0,0x39,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd139[] = {0x02,0x00,0x39,0xC0,0x3A,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd140[] = {0x02,0x00,0x39,0xC0,0x3B,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd141[] = {0x02,0x00,0x39,0xC0,0x3C,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd142[] = {0x02,0x00,0x39,0xC0,0x3D,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd143[] = {0x02,0x00,0x39,0xC0,0x3E,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd144[] = {0x02,0x00,0x39,0xC0,0x3F,0x13,0xFF,0xFF};
static char jd9366_new_video_on_cmd145[] = {0x02,0x00,0x39,0xC0,0x40,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd146[] = {0x02,0x00,0x39,0xC0,0x41,0x1F,0xFF,0xFF};
static char jd9366_new_video_on_cmd147[] = {0x02,0x00,0x39,0xC0,0x42,0x10,0xFF,0xFF};
static char jd9366_new_video_on_cmd148[] = {0x02,0x00,0x39,0xC0,0x43,0x0E,0xFF,0xFF};
static char jd9366_new_video_on_cmd149[] = {0x02,0x00,0x39,0xC0,0x44,0x0C,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd150[] = {0x02,0x00,0x39,0xC0,0x45,0x0A,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd151[] = {0x02,0x00,0x39,0xC0,0x46,0x08,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd152[] = {0x02,0x00,0x39,0xC0,0x47,0x06,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd153[] = {0x02,0x00,0x39,0xC0,0x48,0x04,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd154[] = {0x02,0x00,0x39,0xC0,0x49,0x18,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd155[] = {0x02,0x00,0x39,0xC0,0x4A,0x17,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd156[] = {0x02,0x00,0x39,0xC0,0x4B,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd157[] = {0x02,0x00,0x39,0xC0,0x4C,0x00,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd158[] = {0x02,0x00,0x39,0xC0,0x4D,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd159[] = {0x02,0x00,0x39,0xC0,0x4E,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd160[] = {0x02,0x00,0x39,0xC0,0x4F,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd161[] = {0x02,0x00,0x39,0xC0,0x50,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd162[] = {0x02,0x00,0x39,0xC0,0x51,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd163[] = {0x02,0x00,0x39,0xC0,0x52,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd164[] = {0x02,0x00,0x39,0xC0,0x53,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd165[] = {0x02,0x00,0x39,0xC0,0x54,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd166[] = {0x02,0x00,0x39,0xC0,0x55,0x12,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd167[] = {0x02,0x00,0x39,0xC0,0x56,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd168[] = {0x02,0x00,0x39,0xC0,0x57,0x1F,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd169[] = {0x02,0x00,0x39,0xC0,0x58,0x40,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd170[] = {0x02,0x00,0x39,0xC0,0x5B,0x30,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd171[] = {0x02,0x00,0x39,0xC0,0x5C,0x02,0xFF,0xFF};                                         
static char jd9366_new_video_on_cmd172[] = {0x02,0x00,0x39,0xC0,0x5D,0x40,0xFF,0xFF};
static char jd9366_new_video_on_cmd173[] = {0x02,0x00,0x39,0xC0,0x5E,0x01,0xFF,0xFF};
static char jd9366_new_video_on_cmd174[] = {0x02,0x00,0x39,0xC0,0x5F,0x02,0xFF,0xFF};
static char jd9366_new_video_on_cmd175[] = {0x02,0x00,0x39,0xC0,0x63,0x62,0xFF,0xFF};
static char jd9366_new_video_on_cmd176[] = {0x02,0x00,0x39,0xC0,0x64,0x62,0xFF,0xFF};
static char jd9366_new_video_on_cmd177[] = {0x02,0x00,0x39,0xC0,0x67,0x74,0xFF,0xFF};
static char jd9366_new_video_on_cmd178[] = {0x02,0x00,0x39,0xC0,0x68,0x04,0xFF,0xFF};
static char jd9366_new_video_on_cmd179[] = {0x02,0x00,0x39,0xC0,0x69,0x62,0xFF,0xFF};
static char jd9366_new_video_on_cmd180[] = {0x02,0x00,0x39,0xC0,0x6A,0x66,0xFF,0xFF};
static char jd9366_new_video_on_cmd181[] = {0x02,0x00,0x39,0xC0,0x6B,0x08,0xFF,0xFF};
static char jd9366_new_video_on_cmd182[] = {0x02,0x00,0x39,0xC0,0x6C,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd183[] = {0x02,0x00,0x39,0xC0,0x6D,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd184[] = {0x02,0x00,0x39,0xC0,0x6E,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd185[] = {0x02,0x00,0x39,0xC0,0x6F,0x08,0xFF,0xFF};
static char jd9366_new_video_on_cmd186[] = {0x02,0x00,0x39,0xC0,0xE0,0x03,0xFF,0xFF};
static char jd9366_new_video_on_cmd187[] = {0x02,0x00,0x39,0xC0,0x9B,0x04,0xFF,0xFF};
static char jd9366_new_video_on_cmd188[] = {0x02,0x00,0x39,0xC0,0xAF,0x20,0xFF,0xFF};
static char jd9366_new_video_on_cmd189[] = {0x02,0x00,0x39,0xC0,0xE0,0x04,0xFF,0xFF};
static char jd9366_new_video_on_cmd190[] = {0x02,0x00,0x39,0xC0,0x09,0x10,0xFF,0xFF};
static char jd9366_new_video_on_cmd191[] = {0x02,0x00,0x39,0xC0,0x0E,0x48,0xFF,0xFF};
static char jd9366_new_video_on_cmd192[] = {0x02,0x00,0x39,0xC0,0x2B,0x2B,0xFF,0xFF};
static char jd9366_new_video_on_cmd193[] = {0x02,0x00,0x39,0xC0,0x2E,0x44,0xFF,0xFF};
static char jd9366_new_video_on_cmd194[] = {0x02,0x00,0x39,0xC0,0x41,0xFF,0xFF,0xFF};
static char jd9366_new_video_on_cmd195[] = {0x02,0x00,0x39,0xC0,0x4B,0xFF,0xFF,0xFF};
static char jd9366_new_video_on_cmd196[] = {0x02,0x00,0x39,0xC0,0xE0,0x00,0xFF,0xFF};
static char jd9366_new_video_on_cmd197[] = {0x02,0x00,0x39,0xC0,0xE6,0x02,0xFF,0xFF};
static char jd9366_new_video_on_cmd198[] = {0x02,0x00,0x39,0xC0,0xE7,0x06,0xFF,0xFF};
static char jd9366_new_video_on_cmd199[] = {0x02,0x00,0x39,0xC0,0x51,0xFF,0xFF,0xFF};
static char jd9366_new_video_on_cmd200[] = {0x02,0x00,0x39,0xC0,0x53,0x2C,0xFF,0xFF};
static char jd9366_new_video_on_cmd201[] = {0x02,0x00,0x39,0xC0,0x55,0x01,0xFF,0xFF};
static char jd9366_new_video_on_cmd202[] = {0x02,0x00,0x39,0xC0,0xE0,0x03,0xFF,0xFF};
static char jd9366_new_video_on_cmd203[] = {0x02,0x00,0x39,0xC0,0xAB,0x0E,0xFF,0xFF};
static char jd9366_new_video_on_cmd204[] = {0x02,0x00,0x39,0xC0,0xE0,0x00,0xFF,0xFF};


static char jd9366_new_video_on_exit_sleep[] = {
	0x11, 0x00, 0x05, 0x80
};

static char jd9366_new_video_on_display_on[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd jd9366_new_video_on_command[] = {
{ARRAY_SIZE(jd9366_new_video_on_cmd1), jd9366_new_video_on_cmd1, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd2), jd9366_new_video_on_cmd2, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd3), jd9366_new_video_on_cmd3, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd4), jd9366_new_video_on_cmd4, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd5), jd9366_new_video_on_cmd5, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd6), jd9366_new_video_on_cmd6, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd7), jd9366_new_video_on_cmd7, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd8), jd9366_new_video_on_cmd8, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd9), jd9366_new_video_on_cmd9, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd10), jd9366_new_video_on_cmd10, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd11), jd9366_new_video_on_cmd11, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd12), jd9366_new_video_on_cmd12, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd13), jd9366_new_video_on_cmd13, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd14), jd9366_new_video_on_cmd14, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd15), jd9366_new_video_on_cmd15, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd16), jd9366_new_video_on_cmd16, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd17), jd9366_new_video_on_cmd17, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd18), jd9366_new_video_on_cmd18, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd19), jd9366_new_video_on_cmd19, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd20), jd9366_new_video_on_cmd20, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd21), jd9366_new_video_on_cmd21, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd22), jd9366_new_video_on_cmd22, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd23), jd9366_new_video_on_cmd23, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd24), jd9366_new_video_on_cmd24, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd25), jd9366_new_video_on_cmd25, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd26), jd9366_new_video_on_cmd26, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd27), jd9366_new_video_on_cmd27, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd28), jd9366_new_video_on_cmd28, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd29), jd9366_new_video_on_cmd29, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd30), jd9366_new_video_on_cmd30, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd31), jd9366_new_video_on_cmd31, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd32), jd9366_new_video_on_cmd32, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd33), jd9366_new_video_on_cmd33, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd34), jd9366_new_video_on_cmd34, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd35), jd9366_new_video_on_cmd35, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd36), jd9366_new_video_on_cmd36, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd37), jd9366_new_video_on_cmd37, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd38), jd9366_new_video_on_cmd38, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd39), jd9366_new_video_on_cmd39, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd40), jd9366_new_video_on_cmd40, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd41), jd9366_new_video_on_cmd41, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd42), jd9366_new_video_on_cmd42, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd43), jd9366_new_video_on_cmd43, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd44), jd9366_new_video_on_cmd44, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd45), jd9366_new_video_on_cmd45, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd46), jd9366_new_video_on_cmd46, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd47), jd9366_new_video_on_cmd47, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd48), jd9366_new_video_on_cmd48, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd49), jd9366_new_video_on_cmd49, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd50), jd9366_new_video_on_cmd50, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd51), jd9366_new_video_on_cmd51, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd52), jd9366_new_video_on_cmd52, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd53), jd9366_new_video_on_cmd53, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd54), jd9366_new_video_on_cmd54, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd55), jd9366_new_video_on_cmd55, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd56), jd9366_new_video_on_cmd56, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd57), jd9366_new_video_on_cmd57, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd58), jd9366_new_video_on_cmd58, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd59), jd9366_new_video_on_cmd59, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd60), jd9366_new_video_on_cmd60, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd61), jd9366_new_video_on_cmd61, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd62), jd9366_new_video_on_cmd62, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd63), jd9366_new_video_on_cmd63, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd64), jd9366_new_video_on_cmd64, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd65), jd9366_new_video_on_cmd65, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd66), jd9366_new_video_on_cmd66, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd67), jd9366_new_video_on_cmd67, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd68), jd9366_new_video_on_cmd68, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd69), jd9366_new_video_on_cmd69, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd70), jd9366_new_video_on_cmd70, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd71), jd9366_new_video_on_cmd71, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd72), jd9366_new_video_on_cmd72, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd73), jd9366_new_video_on_cmd73, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd74), jd9366_new_video_on_cmd74, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd75), jd9366_new_video_on_cmd75, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd76), jd9366_new_video_on_cmd76, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd77), jd9366_new_video_on_cmd77, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd78), jd9366_new_video_on_cmd78, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd79), jd9366_new_video_on_cmd79, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd80), jd9366_new_video_on_cmd80, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd81), jd9366_new_video_on_cmd81, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd82), jd9366_new_video_on_cmd82, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd83), jd9366_new_video_on_cmd83, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd84), jd9366_new_video_on_cmd84, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd85), jd9366_new_video_on_cmd85, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd86), jd9366_new_video_on_cmd86, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd87), jd9366_new_video_on_cmd87, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd88), jd9366_new_video_on_cmd88, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd89), jd9366_new_video_on_cmd89, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd90), jd9366_new_video_on_cmd90, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd91), jd9366_new_video_on_cmd91, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd92), jd9366_new_video_on_cmd92, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd93), jd9366_new_video_on_cmd93, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd94), jd9366_new_video_on_cmd94, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd95), jd9366_new_video_on_cmd95, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd96), jd9366_new_video_on_cmd96, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd97), jd9366_new_video_on_cmd97, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd98), jd9366_new_video_on_cmd98, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd99), jd9366_new_video_on_cmd99, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd100), jd9366_new_video_on_cmd100, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd101), jd9366_new_video_on_cmd101, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd102), jd9366_new_video_on_cmd102, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd103), jd9366_new_video_on_cmd103, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd104), jd9366_new_video_on_cmd104, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd105), jd9366_new_video_on_cmd105, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd106), jd9366_new_video_on_cmd106, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd107), jd9366_new_video_on_cmd107, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd108), jd9366_new_video_on_cmd108, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd109), jd9366_new_video_on_cmd109, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd110), jd9366_new_video_on_cmd110, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd111), jd9366_new_video_on_cmd111, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd112), jd9366_new_video_on_cmd112, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd113), jd9366_new_video_on_cmd113, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd114), jd9366_new_video_on_cmd114, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd115), jd9366_new_video_on_cmd115, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd116), jd9366_new_video_on_cmd116, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd117), jd9366_new_video_on_cmd117, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd118), jd9366_new_video_on_cmd118, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd119), jd9366_new_video_on_cmd119, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd120), jd9366_new_video_on_cmd120, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd121), jd9366_new_video_on_cmd121, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd122), jd9366_new_video_on_cmd122, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd123), jd9366_new_video_on_cmd123, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd124), jd9366_new_video_on_cmd124, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd125), jd9366_new_video_on_cmd125, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd126), jd9366_new_video_on_cmd126, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd127), jd9366_new_video_on_cmd127, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd128), jd9366_new_video_on_cmd128, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd129), jd9366_new_video_on_cmd129, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd130), jd9366_new_video_on_cmd130, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd131), jd9366_new_video_on_cmd131, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd132), jd9366_new_video_on_cmd132, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd133), jd9366_new_video_on_cmd133, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd134), jd9366_new_video_on_cmd134, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd135), jd9366_new_video_on_cmd135, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd136), jd9366_new_video_on_cmd136, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd137), jd9366_new_video_on_cmd137, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd138), jd9366_new_video_on_cmd138, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd139), jd9366_new_video_on_cmd139, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd140), jd9366_new_video_on_cmd140, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd141), jd9366_new_video_on_cmd141, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd142), jd9366_new_video_on_cmd142, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd143), jd9366_new_video_on_cmd143, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd144), jd9366_new_video_on_cmd144, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd145), jd9366_new_video_on_cmd145, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd146), jd9366_new_video_on_cmd146, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd147), jd9366_new_video_on_cmd147, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd148), jd9366_new_video_on_cmd148, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd149), jd9366_new_video_on_cmd149, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd150), jd9366_new_video_on_cmd150, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd151), jd9366_new_video_on_cmd151, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd152), jd9366_new_video_on_cmd152, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd153), jd9366_new_video_on_cmd153, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd154), jd9366_new_video_on_cmd154, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd155), jd9366_new_video_on_cmd155, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd156), jd9366_new_video_on_cmd156, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd157), jd9366_new_video_on_cmd157, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd158), jd9366_new_video_on_cmd158, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd159), jd9366_new_video_on_cmd159, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd160), jd9366_new_video_on_cmd160, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd161), jd9366_new_video_on_cmd161, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd162), jd9366_new_video_on_cmd162, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd163), jd9366_new_video_on_cmd163, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd164), jd9366_new_video_on_cmd164, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd165), jd9366_new_video_on_cmd165, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd166), jd9366_new_video_on_cmd166, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd167), jd9366_new_video_on_cmd167, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd168), jd9366_new_video_on_cmd168, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd169), jd9366_new_video_on_cmd169, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd170), jd9366_new_video_on_cmd170, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd171), jd9366_new_video_on_cmd171, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd172), jd9366_new_video_on_cmd172, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd173), jd9366_new_video_on_cmd173, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd174), jd9366_new_video_on_cmd174, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd175), jd9366_new_video_on_cmd175, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd176), jd9366_new_video_on_cmd176, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd177), jd9366_new_video_on_cmd177, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd178), jd9366_new_video_on_cmd178, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd179), jd9366_new_video_on_cmd179, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd180), jd9366_new_video_on_cmd180, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd181), jd9366_new_video_on_cmd181, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd182), jd9366_new_video_on_cmd182, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd183), jd9366_new_video_on_cmd183, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd184), jd9366_new_video_on_cmd184, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd185), jd9366_new_video_on_cmd185, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd186), jd9366_new_video_on_cmd186, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd187), jd9366_new_video_on_cmd187, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd188), jd9366_new_video_on_cmd188, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd189), jd9366_new_video_on_cmd189, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd190), jd9366_new_video_on_cmd190, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd191), jd9366_new_video_on_cmd191, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd192), jd9366_new_video_on_cmd192, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd193), jd9366_new_video_on_cmd193, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd194), jd9366_new_video_on_cmd194, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd195), jd9366_new_video_on_cmd195, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd196), jd9366_new_video_on_cmd196, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd197), jd9366_new_video_on_cmd197, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd198), jd9366_new_video_on_cmd198, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd199), jd9366_new_video_on_cmd199, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd200), jd9366_new_video_on_cmd200, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd201), jd9366_new_video_on_cmd201, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd202), jd9366_new_video_on_cmd202, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd203), jd9366_new_video_on_cmd203, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_cmd204), jd9366_new_video_on_cmd204, 0x01},
{ARRAY_SIZE(jd9366_new_video_on_exit_sleep), jd9366_new_video_on_exit_sleep, 0x78},
{ARRAY_SIZE(jd9366_new_video_on_display_on), jd9366_new_video_on_display_on, 0x14},
};

#define JD9366_NEW_VIDEO_ON_COMMAND 173


static char jd9366_new_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char jd9366_new_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd jd9366_new_video_off_command[] = {
	{0x4, jd9366_new_videooff_cmd0, 0x32},
	{0x4, jd9366_new_videooff_cmd1, 0x78}
};

#define JD9366_NEW_VIDEO_OFF_COMMAND 2


static struct command_state jd9366_new_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info jd9366_new_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info jd9366_new_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration jd9366_new_video_lane_config = {
	4, 0, 1, 1, 1, 1, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t jd9366_new_video_timings[] = {
	0x86, 0x1E, 0x14, 0x00, 0x43, 0x4B, 0x19, 0x21, 0x22, 0x03, 0x04, 0x00
};

static const uint32_t jd9366_14nm_new_video_timings[] = {
	0x1e, 0x1b, 0x04, 0x05, 0x02, 0x03, 0x04, 0xa0,
	0x1e, 0x1b, 0x04, 0x05, 0x02, 0x03, 0x04, 0xa0,
	0x1e, 0x1b, 0x04, 0x05, 0x02, 0x03, 0x04, 0xa0,
	0x1e, 0x1b, 0x04, 0x05, 0x02, 0x03, 0x04, 0xa0,
	0x1e, 0x0d, 0x03, 0x05, 0x02, 0x03, 0x04, 0xa0,
};

static struct panel_timing jd9366_new_video_timing_info = {
	0, 4, 0x0a, 0x1c
};

static struct labibb_desc jd9366_new_video_labibb = {
	0, 1, 5700000, 5700000, 5700000, 5700000, 3, 3, 1, 0
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence jd9366_new_video_reset_seq = {
	{1, 0, 1, }, {20, 50, 100, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
/*static struct backlight jd9366_new_video_backlight = {
	0, 1, 255, 0, 0, 0
};*/

static struct backlight jd9366_new_video_backlight = {
	1, 1, 4095, 100, 1, "PMIC_8941"
};

#define JD9366_NEW_VIDEO_SIGNATURE 0xFFFF

#endif /*_PANEL_JD9366_NEW_VIDEO_H_*/


